apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-replicaset
  labels:
    my-pod: my-jenkins
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      my-pod: my-jenkins
  template:
    metadata:
      labels:
        my-pod: my-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080
