apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  labels:
    app: jenkins-set
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins-set
  template:
    metadata:
      labels:
        app: jenkins-set
    spec:
      volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: local-pvc
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: local-volume
          mountPath: /var/jenkins_home
      securityContext:
        runAsUser: 0
        fsGroup: 0
