apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: myjenkins  
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myjenkins
  template:
    metadata:
      labels:
        app: myjenkins  
    spec:
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: efs-static-pvc
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        volumeMounts: 
        - mountPath: /var/jenkins_home
          name: local-volume
        ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 0
        fsGroup: 0
